@startchen
entity "Кафедра" as chair {
  * chair_id : int
  --
  chair_name : string
}

entity "Преподаватель" as teacher {
  * teacher_id : int
  --
  chair_id : int
  teacher_name : string
  publications : int
}

chair ||--o{ teacher : включает
@endchen
