@startuml
start
:Запуск приложения;
:Инициализация SQLite и импорт CSV;
repeat
  :Показать главное меню;
  :Считать пункт меню;

  switch (Пункт)
    case (1)
      :Показать кафедры;
    case (2)
      :Показать преподавателей;
    case (3)
      :Добавить преподавателя;
    case (4)
      :Редактировать преподавателя;
    case (5)
      :Удалить преподавателя;
    case (6)
      :Открыть меню отчётов;
    case (7)
      :Фильтр по кафедре;
    case (8)
      :Экспорт в CSV;
    case (0)
      :Завершить работу;
  endswitch

repeat while (не 0?) is (да)
stop
@enduml
